-- CLIENT TABLE [*]
CREATE TABLE "CLIENT"(
    "id" SERIAL NOT NULL UNIQUE,
    "FULL_NAME" VARCHAR(255) NOT NULL,
    "BIRTH_DAY" TIMESTAMP NOT NULL,
    "PHONE_NUMBER" VARCHAR(255) NULL,
    "E_MAIL" VARCHAR(255) NOT NULL,
    "PASS" VARCHAR(255) NOT NULL,
    "EMAIL_CONF" BOOLEAN NULL,
    "PHOTO_LINK" VARCHAR(255) NOT NULL,
    "RATE" INT NOT NULL,
    "CLIENT_TYPE" INT NOT NULL
);


-- OBJECT_MEDIA_DATA TABLE [*]
CREATE TABLE "OBJECT_MEDIA_DATA"(
    "id" SERIAL NOT NULL UNIQUE,
    "OBJECT" INT NOT NULL,
    "LONKS" JSON NOT NULL,
    "CREATE_DATE" TIMESTAMP NOT NULL,
    "UPDATE_DATE" TIMESTAMP NULL
);


-- OBJECT_REVIEW TABLE [*]
CREATE TABLE "OBJECT_REVIEW"(
    "id" SERIAL NOT NULL UNIQUE,
    "TENANT" INT NOT NULL,
    "OBJECT" INT NOT NULL,
    "REVIEW_TEXT" TEXT NOT NULL,
    "RATE" INT NOT NULL
);
  

-- CLIENT_RENT_HISTORT TABLE [*]
CREATE TABLE "CLIENT_RENT_HISTORY"(
    "id" SERIAL NOT NULL UNIQUE,
    "LANDLORD" INT NOT NULL,
    "TENANT" INT NOT NULL,
    "OBJECT" INT NOT NULL,
    "RENT_DATE" DATE NOT NULL,
    "LANDLORD_RATE" INT NOT NULL
);


-- PLANED_TRIPS TABLE [*]
CREATE TABLE "PLANED_TRIPS"(
    "id" SERIAL NOT NULL UNIQUE,
    "CLIENT" INT NOT NULL,
    "START_DATE" DATE NOT NULL,
    "FACILITIES" JSON NOT NULL,
    "PRICE" INT NOT NULL,
    "RATE" INT NOT NULL
);


-- BOOKED_OBJECTS TABLE
CREATE TABLE "BOOKED_OBJECTS"(
    "id" SERIAL NOT NULL UNIQUE,
    "LANDLORD" INT NOT NULL,
    "TENANT" INT NOT NULL,
    "OBJECT" INT NOT NULL,
    "BOOKING_DATE" TIMESTAMP NOT NULL
);


-- CLIENT_REVIEW TABLE [*]
CREATE TABLE "CLIENT_REVIEW"(
    "id" SERIAL NOT NULL UNIQUE,
    "LANDLORD" INT NOT NULL,
    "TENANT" INT NOT NULL,
    "REVIEW_TEXT" TEXT NOT NULL,
    "RATE" INT NOT NULL
);


-- BOOKING_HISTORY TABLE [*]
CREATE TABLE "BOOKING_HISTORY"(
    "id" SERIAL NOT NULL UNIQUE,
    "LANDLORD" INT NOT NULL,
    "TENANT" INT NOT NULL,
    "OBJECT" INT NOT NULL,
    "BOOCKING_DATE" DATE NOT NULL,
    "RATE" INT NOT NULL
);


-- RENTED_OBJECTS TABLE [*]
CREATE TABLE "RENTED_OBJECTS"(
    "id" SERIAL NOT NULL UNIQUE,
    "LANDLORD" INT NOT NULL,
    "TENANT" INT NOT NULL,
    "OBJECT" INT NOT NULL,
    "PRICE" INT NOT NULL,
    "END_DATE" DATE NOT NULL
);


-- RENT_OBJECT_ADDRESS TABLE [*]
CREATE TABLE "RENT_OBJECT_ADDRESS"(
    "id" SERIAL NOT NULL UNIQUE,
    "COUNTRY" VARCHAR(255) NOT NULL,
    "SETTELENT" VARCHAR(255) NOT NULL,
    "SETTELENT_TYPE" INT NOT NULL,
    "STREET" VARCHAR(255) NOT NULL,
    "HOUSE_NUMBER" INT NOT NULL,
    "HULL_NUMBER" INT NULL,
    "APPART_NUMBER" INT NULL
);


-- REND_OBJECTS TABLE [*]
CREATE TABLE "REND_OBJECTS"(
    "id" SERIAL NOT NULL UNIQUE,
    "LANDLORD" INT NOT NULL,
    "FULL_ADDRESS" INT NOT NULL,
    "OBJECT_TYPE" INT NOT NULL,
    "FACILITIES" JSON NOT NULL,
    "PRICE" INT NOT NULL,
    "RATE" INT NOT NULL,
    "CREATE_DATE" TIMESTAMP NOT NULL,
    "UPDATE_DATE" TIMESTAMP NOT NULL,
    "LAT" REAL NULL,
    "LONG" REAL NULL
);


-- CLIENT_TYPES TABLE 
CREATE TABLE "CLIENT_TYPES"(
    "id" SERIAL NOT NULL UNIQUE,
    "TYPE_NAME" VARCHAR(255) NOT NULL
);


-- SETTLEMENT_TYPES TABLE
CREATE TABLE "SETTLEMENT_TYPES"(
    "id" SERIAL NOT NULL UNIQUE,
    "TYPES" VARCHAR(255) NOT NULL
);


-- ALTERS FOR ALL TABLES
ALTER TABLE "CLIENT" ADD PRIMARY KEY ("id");
ALTER TABLE "CLIENT" ADD UNIQUE ("E_MAIL");
