
-- ALTERS FOR ALL TABLES
ALTER TABLE "CLIENT" ADD PRIMARY KEY ("id");
ALTER TABLE "CLIENT" ADD UNIQUE ("E_MAIL");

ALTER TABLE "OBJECT_MEDIA_DATA" ADD PRIMARY KEY ("id");
ALTER TABLE "OBJECT_REVIEW" ADD PRIMARY KEY ("id");
ALTER TABLE "CLIENT_RENT_HISTORY" ADD PRIMARY KEY ("id");
ALTER TABLE "PLANED_TRIPS" ADD PRIMARY KEY ("id");
ALTER TABLE "BOOKED_OBJECTS" ADD PRIMARY KEY ("id");
ALTER TABLE "CLIENT_REVIEW" ADD PRIMARY KEY ("id");
ALTER TABLE "BOOKING_HISTORY" ADD PRIMARY KEY ("id");
ALTER TABLE "RENTED_OBJECTS" ADD PRIMARY KEY ("id");
ALTER TABLE "RENT_OBJECT_ADDRESS" ADD PRIMARY KEY ("id");
ALTER TABLE "REND_OBJECTS" ADD PRIMARY KEY ("id");
ALTER TABLE "CLIENT_TYPES" ADD PRIMARY KEY ("id");
ALTER TABLE "SETTLEMENT_TYPES" ADD PRIMARY KEY ("id");


ALTER TABLE public."REND_OBJECTS" ADD CONSTRAINT "REND_OBJECTS_landlord_foreign" FOREIGN KEY("LANDLORD") REFERENCES public."CLIENT"("id");
ALTER TABLE public."OBJECT_MEDIA_DATA" ADD CONSTRAINT "object_media_data_object_foreign" FOREIGN KEY("OBJECT") REFERENCES public."REND_OBJECTS"("id");
ALTER TABLE public."OBJECT_REVIEW" ADD CONSTRAINT "object_review_tenant_foreign" FOREIGN KEY("TENANT") REFERENCES public."CLIENT"("id");
ALTER TABLE public."CLIENT_RENT_HISTORY" ADD CONSTRAINT "client_rent_history_landlord_foreign" FOREIGN KEY("LANDLORD") REFERENCES public."CLIENT"("id");
ALTER TABLE public."CLIENT_RENT_HISTORY" ADD CONSTRAINT "client_rent_history_tenant_foreign" FOREIGN KEY("TENANT") REFERENCES public."CLIENT"("id");
ALTER TABLE public."PLANED_TRIPS" ADD CONSTRAINT "planed_trips_client_foreign" FOREIGN KEY("CLIENT") REFERENCES public."CLIENT"("id");
ALTER TABLE public."BOOKED_OBJECTS" ADD CONSTRAINT "booked_objects_landlord_foreign" FOREIGN KEY("LANDLORD") REFERENCES public."CLIENT"("id");
ALTER TABLE public."BOOKED_OBJECTS" ADD CONSTRAINT "booked_objects_tenant_foreign" FOREIGN KEY("TENANT") REFERENCES public."CLIENT"("id");
ALTER TABLE public."BOOKED_OBJECTS" ADD CONSTRAINT "booked_objects_object_foreign" FOREIGN KEY("OBJECT") REFERENCES public."REND_OBJECTS"("id");
ALTER TABLE public."CLIENT_REVIEW" ADD CONSTRAINT "client_review_landlord_foreign" FOREIGN KEY("LANDLORD") REFERENCES public."CLIENT"("id");
ALTER TABLE public."CLIENT_REVIEW" ADD CONSTRAINT "client_review_tenant_foreign" FOREIGN KEY("TENANT") REFERENCES public."CLIENT"("id");
ALTER TABLE public."RENTED_OBJECTS" ADD CONSTRAINT "rented_objects_landlord_foreign" FOREIGN KEY("LANDLORD") REFERENCES public."CLIENT"("id");
ALTER TABLE public."RENTED_OBJECTS" ADD CONSTRAINT "rented_objects_tenant_foreign" FOREIGN KEY("TENANT") REFERENCES public."CLIENT"("id");
ALTER TABLE public."RENTED_OBJECTS" ADD CONSTRAINT "rented_objects_object_foreign" FOREIGN KEY("OBJECT") REFERENCES public."REND_OBJECTS"("id");
ALTER TABLE public."REND_OBJECTS" ADD CONSTRAINT "REND_OBJECTS_full_address_foreign" FOREIGN KEY("FULL_ADDRESS") REFERENCES public."RENT_OBJECT_ADDRESS"("id");
ALTER TABLE public."CLIENT" ADD CONSTRAINT "client_client_type_foreign" FOREIGN KEY("CLIENT_TYPE") REFERENCES public."CLIENT_TYPES"("id");
ALTER TABLE public."RENT_OBJECT_ADDRESS" ADD CONSTRAINT "rent_object_address_settelent_type_foreign" FOREIGN KEY("SETTELENT_TYPE") REFERENCES public."SETTLEMENT_TYPES"("id");
